#!/usr/bin/env bash
# Copy fresh dist artifacts (simd-tooltips.js + simd-names.json + simd-data.json)
# into ./lib/ so the extension can bundle them. Run after the database is
# regenerated by ../scripts/build_all.sh.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../simd-tooltip/dist"
DEST="$HERE/lib"

if [[ ! -d "$SRC" ]]; then
    echo "error: $SRC not found. Run scripts/build_all.sh first." >&2
    exit 1
fi

mkdir -p "$DEST"
for f in simd-tooltips.js simd-names.json simd-data.json; do
    if [[ -f "$SRC/$f" ]]; then
        cp "$SRC/$f" "$DEST/$f"
        printf '  %12d B  %s\n' "$(wc -c < "$DEST/$f" | tr -d ' ')" "$DEST/$f"
    fi
done
